// Global
export const TOGGLE_NAV = "TOGGLE_NAV";

// Auth

export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";
export const SET_TEMPORARY_TOKEN = "SET_TEMPORARY_TOKEN";
export const UPGRADEACCOUNT = "UPGRADEACCOUNT";
export const UPDATE_PROFILE = "UPDATE_PROFILE";

// Admins [Super Admin-login]

export const FETCH_ADMINS_START_SUPERADMIN = "FETCH_ADMINS_START_SUPERADMIN";
export const FETCH_ADMINS_SUPERADMIN = "FETCH_ADMINS_SUPERADMIN";
export const FETCH_ADMINS_SUCCESS_SUPERADMIN =
  "FETCH_ADMINS_SUCCESS_SUPERADMIN";
export const FETCH_ADMINS_FAILURE_SUPERADMIN =
  "FETCH_ADMINS_FAILURE_SUPERADMIN";

// Dashboard [Admin-login]

export const FETCH_DASHBOARD_START_ADMIN = "FETCH_DASHBOARD_START_ADMIN";
export const FETCH_DASHBOARD_ADMIN = "FETCH_DASHBOARD_ADMIN";
export const FETCH_DASHBOARD_SUCCESS_ADMIN = "FETCH_DASHBOARD_SUCCESS_ADMIN";
export const FETCH_DASHBOARD_FAILURE_ADMIN = "FETCH_DASHBOARD_FAILURE_ADMIN";

// Employees [Admin-login]

export const FETCH_EMPLOYEES_START_ADMIN = "FETCH_EMPLOYEES_START_ADMIN";
export const FETCH_EMPLOYEES_ADMIN = "FETCH_EMPLOYEES_ADMIN";
export const FETCH_EMPLOYEES_SUCCESS_ADMIN = "FETCH_EMPLOYEES_SUCCESS_ADMIN";
export const FETCH_EMPLOYEES_FAILURE_ADMIN = "FETCH_EMPLOYEES_FAILURE_ADMIN";

// Parents [Admin-login]

export const FETCH_PARENTS_START_ADMIN = "FETCH_PARENTS_START_ADMIN";
export const FETCH_PARENTS_ADMIN = "FETCH_PARENTS_ADMIN";
export const FETCH_PARENTS_SUCCESS_ADMIN = "FETCH_PARENTS_SUCCESS_ADMIN";
export const FETCH_PARENTS_FAILURE_ADMIN = "FETCH_PARENTS_FAILURE_ADMIN";

// Places [Admin-login]

export const FETCH_PLACES_START_ADMIN = "FETCH_PLACES_START_ADMIN";
export const FETCH_PLACES_ADMIN = "FETCH_PLACES_ADMIN";
export const FETCH_PLACES_SUCCESS_ADMIN = "FETCH_PLACES_SUCCESS_ADMIN";
export const FETCH_PLACES_FAILURE_ADMIN = "FETCH_PLACES_FAILURE_ADMIN";

// Buses [Admin-login]

export const FETCH_BUSES_START_ADMIN = "FETCH_BUSES_START_ADMIN";
export const FETCH_BUSES_ADMIN = "FETCH_BUSES_ADMIN";
export const FETCH_BUSES_SUCCESS_ADMIN = "FETCH_BUSES_SUCCESS_ADMIN";
export const FETCH_BUSES_FAILURE_ADMIN = "FETCH_BUSES_FAILURE_ADMIN";

// Buses-log [Admin-login]

export const FETCH_BUSES_LOG_START_ADMIN = "FETCH_BUSES_LOG_START_ADMIN";
export const FETCH_BUSES_LOG_ADMIN = "FETCH_BUSES_LOG_ADMIN";
export const FETCH_BUSES_LOG_RUNNING_SUCCESS_ADMIN =
  "FETCH_BUSES_LOG_RUNNING_SUCCESS_ADMIN";
export const FETCH_BUSES_LOG_IDLE_SUCCESS_ADMIN =
  "FETCH_BUSES_LOG_IDLE_SUCCESS_ADMIN";
export const FETCH_BUSES_LOG_EMERGENCY_SUCCESS_ADMIN =
  "FETCH_BUSES_LOG_EMERGENCY_SUCCESS_ADMIN";
export const FETCH_BUSES_LOG_FAILURE_ADMIN = "FETCH_BUSES_FAILURE_ADMIN";

// Schools [SuperAdminMax-login]

export const FETCH_SCHOOLS_START_SUPERADMINMAX =
  "FETCH_SCHOOLS_START_SUPERADMINMAX";
export const FETCH_SCHOOLS_SUPERADMINMAX = "FETCH_SCHOOLS_SUPERADMINMAX";
export const FETCH_SCHOOLS_SUCCESS_SUPERADMINMAX =
  "FETCH_SCHOOLS_SUCCESS_SUPERADMINMAX";
export const FETCH_SCHOOLS_FAILURE_SUPERADMINMAX =
  "FETCH_SCHOOLS_FAILURE_SUPERADMINMAX";

//  USER ACCOUNT

// Home Page
export const FETCH_HOUSES_START = "FETCH_HOUSES_START";
export const FETCH_HOUSES = "FETCH_HOUSES";
export const FETCH_HOUSES_SUCCESS = "FETCH_HOUSES_SUCCESS";
export const FETCH_HOUSES_FAILURE = "FETCH_HOUSES_FAILURE";

// MY houses Page
export const FETCH_MY_HOUSES = "FETCH_MY_HOUSES";
export const FETCH_MY_HOUSES_START = "FETCH_MY_HOUSES_START";
export const FETCH_MY_HOUSES_SUCCESS = "FETCH_MY_HOUSES_SUCCESS";
export const FETCH_MY_HOUSES_FAILURE = "FETCH_MY_HOUSES_FAILURE";

// Requests Page
export const FETCH_REQUESTS_START = "FETCH_REQUESTS_START";
export const FETCH_REQUESTS = "FETCH_REQUESTS";
export const FETCH_REQUESTS_SUCCESS = "FETCH_REQUESTS_SUCCESS";
export const FETCH_REQUESTS_FAILURE = "FETCH_REQUESTS_FAILURE";
